### ISSUE TITLE
No test for a working C11 compiler

### ISSUE THREAD

**Issue by dwatteau** [cmus/cmus#626]
This is with cmus v2.8.0-rc0 on OpenBSD -current, trying to build with GCC 4.2.1, which is still the default compiler at the moment (it's possible to build ports with a newer compiler when needed, however).

cmus now uses `<stdatomic.h>`, which requires a C11 compiler, AFAIK.

However, `configure` doesn't reject non-C11 compilers, such as GCC 4.2.1.

It justs removes a lot of flags (since `-std=gnu11` and the warnings flags are tested at the same time), and the `ffmpeg.c` build test fails, since it also requires a working `-std=gnu11`:

```
checking for CFLAGS -std=gnu11 -pipe -Wall -Wshadow -Wcast-align -Wpointer-arith -Wwrite-strings -Wundef -Wmissing-prototypes -Wredundant-decls -Wextra -Wno-sign-compare -Wformat-security... no

[...]

checking for successful build of ffmpeg.c... no
```

The build then fails this way:
```
cc -c -O2 -pipe [some flags, but no -std=XXX] -o ape.o ape.c
In file included from ape.c:24:
utils.h: In function 'strscpy':
utils.h:322: error: 'for' loop initial declaration used outside C99 mode
```

Of course, if you force `-std=gnu99`, it's not going to be enough:
```
cc -c -O2 -pipe -std=gnu99 [some flags] -o buffer.o buffer.c
In file included from buffer.c:21:
locking.h:23:23: warning: stdatomic.h: No such file or directory
In file included from buffer.c:21:
locking.h:26: error: expected ':', ',', ';', '}' or '__attribute__' before 'tail'
```

So there's **no problem** requiring a C11 compiler here, but I think `configure` should just test for a working C11 compiler, and then abort at the earliest possible stage if it's not found.

**Comment by mahkoh** [comment]
PR's fixing this and #625 would be accepted.

>GCC 4.2.1, which is still the default compiler at the moment

For what purpose?

**Comment by dwatteau** [comment]
> PRs fixing this and #625 would be accepted.

See  #629 for this. Hope it's good.

> For what purpose?

On OpenBSD, GCC 4.2.1 is still the *base* system compiler, at the moment. The reason for this is that the project doesn't want GPLv3 code in its base system, so newer GCC releases are excluded. There's some ongoing work to switch to clang, but GCC 4.2.1 will probably remain the base compiler for a long time for the platforms where clang is not usable.

But cmus is not part of the *base* system, it's part of the *ports* system. While ports are implicitly encouraged to use the base system compiler when possible, there's no problem in requiring a newer GCC/clang if a port really needs it. Since the base system compiler is now 10+ years old, that's becoming more frequent and understable.

**Comment by mahkoh** [comment]
> The reason for this is that the project doesn't want GPLv3 code in its base system, so newer GCC releases are excluded.

That is clear but why not use clang.

**Comment by nefthy** [comment]
Since we need a working c11 compiler, we should test for one in the configure script.

**Comment by flyingmutant** [comment]
Fixed in #629.
